os: osx
language: bash

git:
  depth: false

before_install:
  - brew tap includeos/includeos

install:
  - brew install includeos

before_script:
  - conan config install https://github.com/includeos/conan_config.git
  - git clone https://github.com/includeos/hello_world

script:
  - conan install hello_world -pr apple-clang-10-macos-toolchain
  - source activate.sh
  - cmake hello_world
  - cmake --build
  - boot hello
  - |
    set +e
    pkill -9 -P $$ &> /dev/null || true
    exit $1
